name: run-tests

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile tests
      run: make tests
    
    - name: Set execute permission for run-tests.sh script
      run: chmod a+x ./scripts/run-tests.sh

    - name: Run tests
      run: ./scripts/run-tests.sh
